# Generated by Django 5.2.17 on 2026-10-06 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em atendimento'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='solicitacoes.categoria')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': 'solicitações',
                'db_table': 'solicitacao',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em atendimento'), ('CONCLUIDO', 'Concluído')], max_length=20)),
                ('status_novo', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em atendimento'), ('CONCLUIDO', 'Concluído')], max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_de_status', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='solicitacoes.solicitacao')),
            ],
            options={
                'verbose_name': 'histórico de status',
                'verbose_name_plural': 'históricos de status',
                'db_table': 'historico_status',
                'ordering': ['alterado_em', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['status'], name='solicitacao_status_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['criado_em'], name='solicitacao_criado_em_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ABERTO', 'EM_ATENDIMENTO', 'CONCLUIDO'])), name='solicitacao_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='historicostatus',
            constraint=models.CheckConstraint(condition=models.Q(('status_anterior', models.F('status_novo')), _negated=True), name='historico_status_mudou'),
        ),
    ]
